/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "CyScBoostClk.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "FlowSensorSig_aliases.h"
#include "FlowSensorSig.h"
#include "UART.h"
#include "pHADC.h"
#include "pH_aliases.h"
#include "pH.h"
#include "pHSampleTimer.h"
#include "pHSampleTimerISR.h"
#include "Clock_2.h"
#include "PingSensorTrigCounter.h"
#include "PingSensorTrigISR.h"
#include "pHUpEcho_aliases.h"
#include "pHUpEcho.h"
#include "PingSensorControl.h"
#include "PingSensorEchoTimer.h"
#include "PingSensorEchoISR.h"
#include "WaterEcho_aliases.h"
#include "WaterEcho.h"
#include "pHUpTrig_aliases.h"
#include "pHUpTrig.h"
#include "pHDownTrig_aliases.h"
#include "pHDownTrig.h"
#include "NutsTrig_aliases.h"
#include "NutsTrig.h"
#include "WaterTrig_aliases.h"
#include "WaterTrig.h"
#include "pHDownEcho_aliases.h"
#include "pHDownEcho.h"
#include "NutsEcho_aliases.h"
#include "NutsEcho.h"
#include "LevelSelect.h"
#include "PingSensorTrigControl.h"
#include "PingSensorSampleTimer.h"
#include "Clock_1.h"
#include "SensorComTxUART.h"
#include "timer_clock_1.h"
#include "SensorDataComTimer.h"
#include "SensorDataComISR.h"
#include "DataComTxInv_aliases.h"
#include "DataComTxInv.h"
#include "PingSensorSampleTimerISR.h"
#include "FreeRunningTimer.h"
#include "FlowSenseCaptureISR.h"
#include "WaterResEcho_aliases.h"
#include "WaterResEcho.h"
#include "WaterResTrig_aliases.h"
#include "WaterResTrig.h"
#include "FlowSenseTimeOutISR.h"
#include "FlowSenseTimeOutTimer.h"
#include "isr_rx.h"
#include "ECSenseDataRxISR.h"
#include "ECSenseUART.h"
#include "ECSenseRxInv_aliases.h"
#include "ECSenseRxInv.h"
#include "ECSenseControlReg.h"
#include "ECControl_aliases.h"
#include "ECControl.h"
#include "SenseSwitchTimer.h"
#include "SenseSwitchTimerISR.h"
#include "Clock_3.h"
#include "UART_IntClock.h"
#include "pHADC_IRQ.h"
#include "pHADC_theACLK.h"
#include "SensorComTxUART_IntClock.h"
#include "ECSenseUART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

